local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
local Window = Library.CreateLib("ExecHub - Create: Nghia Dark", "Midnight")
---Tổng Hợp Script
local Tab = Window:NewTab("Script No Key")
local Section = Tab:NewSection("Discord Để Nhận Thông Báo:https://discord.gg/vhNWmBS8")

Section:NewButton("AnDepZai Hub", "OG", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/AnDepZaiHub/AnDepZaiHubBeta/main/AnDepZaiHubBeta.lua"))()
end)
Section:NewButton("W-azure", "O", function()
loadstring(game:HttpGet("https://api.luarmor.net/files/v3/loaders/3b2169cf53bc6104dabe8e19562e5cc2.lua"))()
end)
Section:NewButton("Red Hub", "G", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/REDzHUB/BloxFruits/main/redz9999"))()
end)
Section:NewButton("MtrietHub", "G", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/Minhtriettt/Free-Script/main/MTriet-Hub.lua"))()
end)
